---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        exclude: tests
        args: [--skip, "B322,B110,B605,B607"]  # ignore assert_used and B110

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort

#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.13.5
#    hooks:
#       - id: pylint
#         args:
#           - --max-line-length=120
#           - --ignore-imports=yes
#           # ignore  C0116: Missing function or method docstring
#           - --disable=C0116
#           - -d duplicate-code
