name: Test behavex in latest python versions


on: [push, pull_request]

jobs:
  test-behavex:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install behavex
        run: |
          python -m pip install --upgrade pip
          pip install behavex

      - name: Verify behavex command
        run: behavex ./tests/features/*.feature
